# Generated by Django 5.0.6 on 2024-12-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jntu',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='GMRIT', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='jntuno',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('contest_type', models.PositiveIntegerField()),
                ('venue', models.CharField(max_length=30)),
                ('poster', models.ImageField(null=True, upload_to='')),
                ('winner', models.CharField(max_length=40, null=True)),
                ('runner', models.CharField(max_length=40, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
