# Generated by Django 5.0.6 on 2024-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='contests',
            name='runner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='winner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
