# Generated by Django 5.0.6 on 2024-12-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contests_created_by_alter_contests_runner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='poster',
            field=models.ImageField(null=True, upload_to='contest_posters/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
