# Generated by Django 5.0.6 on 2025-02-07 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='winner',
        ),
        migrations.AddField(
            model_name='contests',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='contest_winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
