# Generated by Django 5.0.6 on 2025-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('lives', models.PositiveIntegerField(default=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timelimit', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.PositiveIntegerField()),
                ('code', models.TextField()),
                ('output', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(null=True)),
                ('memory', models.PositiveIntegerField(null=True)),
                ('json_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tempcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.TextField(default='#include<stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}')),
                ('python', models.TextField(default='#write your code here')),
                ('cpp', models.TextField(default='#include<iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}')),
                ('java', models.TextField(default='public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}')),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('hidden', models.BooleanField(default=True)),
            ],
        ),
    ]
