# Generated by Django 5.0.6 on 2025-03-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compticode', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_participants', to='core.contests'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_questions', to='core.contests'),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_submissions', to='compticode.participant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_submissions', to='compticode.questions'),
        ),
        migrations.AddField(
            model_name='tempcode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_temporary_codes', to='compticode.participant'),
        ),
        migrations.AddField(
            model_name='tempcode',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_temporary_codes', to='compticode.questions'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compticode_testcases', to='compticode.questions'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'contest')},
        ),
    ]
