# Generated by Django 5.0.6 on 2025-03-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compticode', '0003_alter_submission_question_alter_tempcode_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testcases',
        ),
    ]
