# Generated by Django 5.0.6 on 2025-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0005_alter_tempcode_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
