# Generated by Django 5.0.6 on 2025-01-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0006_submission_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='data',
        ),
        migrations.AddField(
            model_name='submission',
            name='json_data',
            field=models.JSONField(default={'success': False}),
        ),
    ]
