# Generated by Django 5.0.6 on 2025-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0007_remove_submission_data_submission_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
