# Generated by Django 5.0.6 on 2025-03-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcode',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_codes', to='core.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.question'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='core.question'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
