# Generated by Django 5.0.6 on 2024-12-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0002_questions_lives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='lang',
            new_name='language',
        ),
    ]
