# Generated by Django 5.0.6 on 2025-01-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0003_rename_descreption_questions_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.TextField(verbose_name='#include<stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}')),
                ('python', models.TextField(default='#write your code heare')),
                ('cpp', models.TextField(default='#include<iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}')),
                ('java', models.TextField(default='public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_codes', to='codelife.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_codes', to='codelife.questions')),
            ],
        ),
    ]
