# Generated by Django 5.0.6 on 2025-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelife', '0008_alter_submission_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcode',
            name='python',
            field=models.TextField(default='#write your code here'),
        ),
    ]
